<?php


/**
 * Implementation of hook_menu().
 */

function advancemenu_menu() {
  $menuitems['menudemo'] = array(
    'title' => 'My Menu',
    'page callback' => 'advancemenu_mymenu_page_callback',
    'page arguments' => array('Product','view'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $menuitems['menudemo/producttab'] = array(
    'title' => 'Product Tab',
    'page callback' => 'advancemenu_mymenu_tabbed_page_callback',
    'page arguments' => array('Main Product Tab'),
    'access callback' => TRUE,
  );

  $menuitems['menudemo/producttab/default'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'Default Product Tab',
    'weight' => 1,
  );

  $menuitems['menudemo/producttab/viewall'] = array(
    'title' => 'View All',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'advancemenu_mymenu_tabbed_viewall_page_callback',
    'page arguments' => array('View all Product Tab'),
    'access callback' => TRUE,
    'weight' => 2,
  );

  $menuitems['menudemo/producttab/editall'] = array(
    'title' => 'Edit All',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'advancemenu_mymenu_tabbed_editall_page_callback',
    'page arguments' => array('Edit all Product Tab'),
    'access callback' => TRUE,
    'weight' => 3,
  );

  return $menuitems;
}

function advancemenu_mymenu_page_callback($firstparameter = '',$secondparameter = '') {

  $result = 'My Menu URl was hit';
  $result .= '<br> The first Parameter passed to the url is :<b>'.$firstparameter.'</b>';
  $result .= '<br> The Second Parameter passed to the url is : <b>'.$secondparameter.'</b>';
  return $result;
}

function advancemenu_mymenu_tabbed_page_callback($firstparameter='') {

  $result = 'Tabbed Menu';
  $result .= '<h2> The Product Tab for Menu Items</h2>';
  $result .= '<br> The menu Clicked is : <b>'.$firstparameter.'</b>';

  return $result;
}

function advancemenu_mymenu_tabbed_viewall_page_callback($fitsparameter=''){
  $result = 'View All Tab Menu';
  $result .= '<br> The menu clicked is : <b>'.$fitsparameter.'</b>';
  return $result;
}

function advancemenu_mymenu_tabbed_editall_page_callback($firstparameters='') {
  $result = 'Edit All Tab Menu';
  $result .= '<br> The Clicked Menu is : <b>'.$firstparameters.'</b>';
  return $result;
}